### ISSUE TITLE
Typora-PicGo Upload Failed

### ISSUE THREAD

**Issue by lzskyline** [typora/PicGo-cli#2]
![image](https://user-images.githubusercontent.com/9845170/75328715-667ec700-58b9-11ea-9c5e-875fd1e20b8f.png)

[PicGo INFO]: Before transform
[PicGo INFO]: Transforming...
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading...
[PicGo WARN]: failed
[PicGo ERROR]: Error: API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.

**Comment by abnerlee** [comment]
see https://github.com/PicGo/PicGo-Core/issues/30

Or use other image service other than the default one

**Comment by lzskyline** [comment]
> see [PicGo/PicGo-Core#30](https://github.com/PicGo/PicGo-Core/issues/30)
> 
> Or use other image service other than the default one

PicGo-Core is already supported but does not compile target programs that support Windows. Do you have plans to upgrade PicGo-Core?

Also, I didn't find any detailed tutorials on PicGo-Core setting files, so I don't know how to change other image services or input token.
![image](https://user-images.githubusercontent.com/9845170/75336986-173f9300-58c7-11ea-9c2f-92c5488ee1b0.png)
